### ISSUE TITLE
Media width/height is ignored

### ISSUE THREAD

**Issue by majernik** [codemonkey1988/responsive-images#14]
If i set a width or height in the f:media element, these parameters are ignored and the default width/height is used

`<f:media file="{file}" width="150" height="150" />`

**Comment by codemonkey1988** [comment]
Hi,

this is currently the expected behavior. Width and height attributes are being ignored in favor for the configured values. This is because I want to provide a single point of configuration. Is some images sizes are set in the configuration and some in the ViewHelper, it is tricky to debug.

If I understand you correctly, your expectation is, that the given values will override the default values given in the configuration, is that correct?

**Comment by majernik** [comment]
By every Media element a user can set a width or height and these values are not used. The configuration cannot reflect all possible outcomes and as long as this TYPO3 standard feature is there and user can set those dimensions, then the extension should reflect it too.

**Comment by codemonkey1988** [comment]
The problem is that the MediaViewHelper will of course generate multiple images. So it is difficult to define, for what resulting image the attributes will be used. Overriding the default image size (the fallback img Tag) will not make sense because it is used only for Browsers which do not support picture Tag (IE or Edge < 13) or when no media query matches the current screen size (but in this case, you should adjust your configuration). That's why I decided to ignore these attributes completely. I can add a notice in the readme for that to make it more clear..

But I can see when using the option `disablePictureTag` in the MediaViewHelper, it should be possible to set dimensions using width and height attributes which is not the case right now.

When you have a use-case for this, please tell me the expected behavior you wish to get setting the attributes. I would like to know what the rendered result should look like. Maybe I'm missing that scenario.

**Comment by majernik** [comment]
I have missed that option. One can always check in the template, if the width or height is set and just use the `disablePictureTag` option. Thanks for the hint!
